### ISSUE TITLE
[Bug] Gem of the Magnum is giving multiplicative toughness increases instead of additive

### ISSUE THREAD

**Issue by ACE1337x** [ChloePrime/Apotheosis_Modern_Ragnarok#4]
"Gem of the Magnum" is giving multiplicative toughness increases instead of additive, resulting in insane toughness values when slotted in all armor pieces

**Comment by ChloePrime** [comment]
Fixed in #6

**Comment by ACE1337x** [comment]
Thanks for the quick fix!
