### ISSUE TITLE
[Bug] "Brawler's Gem" is giving "Attack Damage" instead of "Bullet Damage" for firearms

### ISSUE THREAD

**Issue by ACE1337x** [ChloePrime/Apotheosis_Modern_Ragnarok#5]
[Bug] "Brawler's Gem" is giving "Attack Damage" instead of "Bullet Damage" for firearms

**Comment by ChloePrime** [comment]
This is intended.
Use `Gem of Magnum` or `Gem of Ballast` to add bullet damages.0

**Comment by ACE1337x** [comment]
I don't think "Attack Damage" does anything for firearms? The I think the "Firearms:" bonus for "Brawler's Gem" should be changed...

**Comment by ChloePrime** [comment]
Most big guns can do melee damage by pressing `V`, some of them can even install bayonets

**Comment by ACE1337x** [comment]
Ohhhh good to know! Thank you!
